### ISSUE TITLE
Ban command not working.

### ISSUE THREAD

**Issue by 4345dgfsd** [AzisPT/HaxRooms#2]
Hi there, it's me again! 
I was testing out the room and stuff, and i have to say, i'm impressed. It's really cool.

Now i decided to try the !ban command for admins, i did the format properly and it indeed **does ban the player with the reason, and expiry date of ban.** 
But, **the player can just join back and login again as if they weren't banned? (Same name and everything)**
I checked around the code and i think it might be the 15 ms delay of some sort **around line 371 in room.ts file**, i'm not sure.

This project is very underrated, and it deserves more recognition, great work! :D

**Comment by AzisPT** [comment]
Seems odd, it always worked with me, what is the time that you have in the MySQL? And the time that you have on the machine you are running the server with (it should be the same tho)? I had some problems in the past when the hour changed, look into that.

**Comment by 4345dgfsd** [comment]
Yes, it appears to be that, it sets the time 2 hours earlier so the banned player gets unbanned instantly. How can i change my time to be exactly the same as system time? Thanks :D

**Comment by AzisPT** [comment]
Is your MySQL server running in the same system the haxball room is running from?

If yes stop MySQL from running, go to `C:\ProgramData\MySQL\MySQL Server 8.0`

and open `my.ini`

find the section `[mysqld]`

and try to find `default-time-zone=`

and switch it to whatever you need it to be.

Start MySQL server again.

If this doesn't work please check on the internet on how to change the timezone of the MySQL server, because it usually defaults to system timezone I don't understand how it could be different.

**Comment by 4345dgfsd** [comment]
Hey there, I managed to figure it out, I found the fix in this [website](https://dba.stackexchange.com/questions/120945/how-do-i-resolve-this-error-error-1298-hy000-unknown-or-incorrect-time-zone). Incase anyone else might get this problem. Thank you for reaching out anyways :D

**Comment by 4345dgfsd** [comment]
Well, it techincally works, but the ban system is still -2 hours behind my current time, when i go into the  my.ini file, the "default-time-zone=) isn't there, and it doesn't seem to work even if i add it in myself.

**Comment by AzisPT** [comment]
Well in that case I can't help you because the problem is not with my project, you need to check what's wrong in your system/MySQL configuration

**Comment by 4345dgfsd** [comment]
Okay, thank you very much. :D
